### PR TITLE
api-cli: add option to skip waiting for tx inclusion

### PR DESCRIPTION
**Pull request by andresilva**

### CODE REVIEW

**Comment by andresilva** [comment]
This is not a very common use-case, but when the chain is not authoring blocks too often (e.g. if finality is lagging) we might want to just push a tx and forget it.

**Comment by andresilva** [comment]
I wasn't able to test this, I tried to run it as follows:

```
❯ yarn run:api query.system.account 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './cli.cjs'
Require stack:
- /home/andre/dev/parity/polkadotjs-tools/packages/api-cli/src/api.ts
- /home/andre/dev/parity/polkadotjs-tools/packages/api-cli/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/andre/dev/parity/polkadotjs-tools/packages/api-cli/src/api.ts:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/home/andre/dev/parity/polkadotjs-tools/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .ts] (/home/andre/dev/parity/polkadotjs-tools/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/andre/dev/parity/polkadotjs-tools/packages/api-cli/src/api.ts',
    '/home/andre/dev/parity/polkadotjs-tools/packages/api-cli/src/index.js'
  ]
}
```

**Comment by jacogr** [comment]
Thank you. the above error is very weird. Will check my side as well.

**Review by jacogr — APPROVED** [review]

**Comment by jacogr** [comment]
Sorry for the long delay in merging this - the issue you had was actually that master was a bit broken, i.e. it didn't play quite nice with the current API. That was only fixed yesterday, so there has been a, erm, "slight delay" here.

**Comment by andresilva** [comment]
No worries, I have an idea about the size of your PR queue 😛

**Comment by jacogr** [comment]
PR queue is not the issue, the issues is the issues queue - which makes me lose track of the rest :)

**Pull request merged**
