### PR TITLE
Add sudo-cli tool for executing commands as superuser

### PR DESCRIPTION
**Pull request by coriolinus**
Largely a copy-paste job from api-cli, with variations from
https://polkadot.js.org/api/examples/promise/10_upgrade_chain/

Note to reviewers: I have never before written any Javascript, let alone Typescript; I am certain that there exist problems in this code which I don't know enough to spot. I am also fairly confident that I have not yet stripped out all inessential code from the module. Please be thorough and pedantic while reviewing; that's how I'll learn best.

### CODE REVIEW

**Comment by jacogr** [comment]
Why not add a `--sudo` flag to the existing cli that always executes the commands via the sudo.sudo call?

**Comment by coriolinus** [comment]
A --sudo flag would interact in complicated ways with the other existing
flags --seed and --sign. I don't know how it should interact with --info.

At my level of JS proficiency, I'm still trying to eliminate all complexity
wherever possible, which in this case means writing a single purpose tool
instead of adding a new flag to the existing one.

**Comment by jacogr** [comment]
They problem is that all code needs to be maintained and there is only x hours in any given day - the same but slightly different just adds overhead and more places to copy to. 

I do understand the familiarity aspect - so it is a good test bed anyway. But sadly won’t be merged here standalone.

**Comment by coriolinus** [comment]
Closing in favor of #102.

**Pull request closed without merging**
